name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    name: "${{ matrix.os }} - ${{ matrix.node-version }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      fail-fast: false
      matrix:
        broccoli-version: ["0.16.9", "1.0.0", "1.1.0", "2.0.0", "2.1.0", "2.2.0", "2.3.0", "3.0.1", "3.1.2"]
        node-version: [10.x, 12.x, 14.x]
        os: ['windows', 'ubuntu']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn install broccoli@${{matrix.broccoli-version}}
    - run: yarn lint
    - run: yarn test
