name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    name: "${{ matrix.os }} - ${{ matrix.node-version }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        os: ['windows', 'ubuntu']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
